#!/bin/bash

# set local directory to Kidesktop-folder
cd "$(dirname "$0")"

if [ "$1" = "full" ]
then
	# copy background-image to splash-screen
	sudo cp -f public/resources/bg.png /usr/share/plymouth/themes/pix/splash.png

	# remove resolv.conf and set hosts-entries
	sudo php init.php &

	# kill panel for fullscreen-mode
	sudo killall lxpanel

	# kill desktop-manager
	sudo killall pcmanfm
fi
nohup sudo /etc/init.d/apache2 stop 2>/dev/null

nohup php tools/samba.php 2>/dev/null

# start websocket-server as daemon
nohup php server.php start -d 2>/dev/null

# start chromium-browser and point to websocket-server
nohup chromium-browser \
--disable-translate \
--disable-autofill-keyboard-accessory-view \
--disable-default-apps \
--disable-extensions \
--disable-infobars \
--disable-notifications \
--disable-prompt-on-repost \
--disable-popup-blocking \
--app=http://localhost:2022/?$1 2>/dev/null

# stop websocket-server
nohup php server.php stop 2>/dev/null

if [ "$1" = "full" ]
then
	# restart panel
	lxpanel --profile LXDE-pi &

	# restart desktop-manager
	pcmanfm --desktop --profile LXDE-pi &

	# copy resolv.conf back from backup
	sudo cp -f /etc/resolv.conf.orig /etc/resolv.conf
fi

